#!/bin/sh
sudo yum update -y
sudo yum install -y git
sudo yum install -y subversion
sudo yum install -y vim-enhanced
sudo yum install -y wget
sudo yum install -y lynx
sudo yum install -y man
sudo yum install -y man-pages
sudo yum install -y make
sudo yum install -y gcc-c++
sudo yum install -y gdb
sudo yum install -y valgrind
sudo yum install -y strace
sudo yum install -y ltrace
sudo yum install -y systemtap
sudo yum install -y tree
sudo yum install -y sysstat
sudo yum install -y dstat
sudo yum install -y yum-utils
sudo yum install -y lrzsz
sudo yum install -y ctags
sudo yum install -y cscope
sudo yum install -y bind-utils
sudo yum install -y tcpdump
sudo yum install -y redhat-lsb-core
sudo yum install -y java-openjdk
sudo yum install -y lsof
sudo yum install -y httpd-tools
sudo yum install -y nc
sudo yum install -y ghostscript
sudo yum install -y graphviz
sudo yum install -y ntpdate
sudo yum install -y doxygen
sudo yum install -y libstdc++-docs
sudo yum install -y unix2dos
sudo yum install -y dos2unix
sudo yum install -y mtr

sudo yum install -y boost-devel
sudo yum install -y zlib-devel
sudo yum install -y pcre-devel
sudo yum install -y libcurl-devel
sudo yum install -y openssl-devel
sudo yum install -y mysql-devel
