#!/bin/sh
CMD_NAME=$(basename $0)

if [ $# -lt 1 ]
then
    echo "${CMD_NAME} [libname1] [libname2] ..."
    exit
fi

for LIBNAME in $*
do
    if [ -f /lib/${LIBNAME} ]
    then
        cp -f /lib/${LIBNAME} .
    elif [ -f /usr/lib/${LIBNAME} ]
    then
        cp -f /usr/lib/${LIBNAME} .
    fi
done

