#!/usr/bin/python3
# 抽取PL/SQL中的骨干信息，包括Insert、Merge、Update、Delete、Truncate、Open For（游标）、Select
import sys
import re

def split_sentences(filename):
    with open(filename, 'r', encoding='gb18030') as file:
        text = file.read()

    text = remove_comments(text)
    sentences = text.split(';')
    return sentences

def remove_comments(text):
    # 删除 /*注释*/
    start_index = text.find("/*")
    while start_index != -1:
        end_index = text.find("*/", start_index + 2)
        if end_index != -1:
            text = text[:start_index] + text[end_index + 2:]
        else:
            text = text[:start_index]
        start_index = text.find("/*")

    # 删除 --注释
    pattern = r"--.*?$"
    text = re.sub(pattern, "", text, flags=re.MULTILINE)
    return text

def find_procedure(text):
    pattern = r'procedure\s+(\w+)'
    match = re.search(pattern, text, re.IGNORECASE)
    if match:
        return True, match.group(1)
    else:
        return False, ""
    
def find_function(text):
    pattern = r'function\s+(\w+)'
    match = re.search(pattern, text, re.IGNORECASE)
    if match:
        return True, match.group(1)
    else:
        return False, ""
    
def find_insert(text):
    pattern = r'insert\s+.*?into\s+(\w+)'
    match = re.search(pattern, text, re.IGNORECASE)
    if match:
        table_name = match.group(1)
        return True, table_name
    else:
        return False, ""
    
def find_merge(text):
    pattern = r'merge\s+.*?into\s+(\w+)'
    match = re.search(pattern, text, re.IGNORECASE)
    if match:
        table_name = match.group(1)
        return True, table_name
    else:
        return False, ""

def find_update(text):
    pattern = r'\bupdate\s+(\w+)'
    match = re.search(pattern, text, re.IGNORECASE)
    if match:
        table_name = match.group(1)
        return True, table_name
    else:
        return False, ""

def find_delete(text):
    pattern = r'delete\s+from\s+(\w+)'
    match = re.search(pattern, text, re.IGNORECASE)
    if match:
        table_name = match.group(1)
        return True, table_name
    else:
        return False, ""
    
def find_truncate(text):
    pattern = r'truncate\s+table\s+(\w+)'
    match = re.search(pattern, text, re.IGNORECASE)
    if match:
        table_name = match.group(1)
        return True, table_name
    else:
        return False, ""
    
def find_open_cursor(text):
    pattern = r'open\s+(\w+)\s+for'
    match = re.search(pattern, text, re.IGNORECASE)
    if match:
        cursor_name = match.group(1)
        return True, cursor_name
    else:
        return False, ""
    
def find_select(text):
    result = ""
    select_content = ""
    is_select = False
    do_output = False
    while text:
        if re.match(r"^select", text, re.IGNORECASE):
            result += "SELECT ... "
            is_select = True
            do_output = False
            text = text[len('select'):]
            continue
        if is_select and re.match(r"^from", text, re.IGNORECASE):
            pattern = r'\binto\s+(\w+)'
            match = re.search(pattern, select_content, re.IGNORECASE)
            if match:
                var_name = match.group(1)
                result += ("INTO %s " % var_name)
            select_content = ""
            
            result += "FROM "
            is_select = False
            do_output = True
            text = text[len('from'):]
            continue
        if do_output:
            result += text[0]
        if is_select:
            select_content += text[0]
        text = text[1:]
    return result

if __name__ == '__main__':
    if len(sys.argv) < 2:
        print("ExtractSQL [filename]")
        sys.exit(1)

    filename = sys.argv[1]
    sentences = split_sentences(filename)
    for sentence in sentences:
        found_any = False

        found_proc, procname = find_procedure(sentence)
        if found_proc:
            print("***   PROCEDURE %s" % procname)
            found_any = True

        found_func, funcname = find_function(sentence)
        if found_func:
            print("***   FUNCTION %s" % funcname)
            found_any = True

        found_insert, insert_table_name = find_insert(sentence)
        if found_insert:
            print("INSERT INTO %s" % insert_table_name)
            found_any = True

        found_merge, merge_table_name = find_merge(sentence)
        if found_merge:
            print("MERGE INTO %s" % merge_table_name)
            found_any = True
        
        found_update, update_table_name = find_update(sentence)
        if found_update:
            print("UPDATE %s SET ..." % update_table_name)
            found_any = True
        
        found_delete, delete_table_name = find_delete(sentence)
        if found_delete:
            print("DELETE FROM %s WHERE ..." % delete_table_name)
            found_any = True
        
        found_truncate, truncate_table_name = find_truncate(sentence)
        if found_truncate:
            print("TRUNCATE TABLE %s" % truncate_table_name)
            found_any = True
        
        found_open_cursor, cursor_name = find_open_cursor(sentence)
        if found_open_cursor:
            print("OPEN %s FOR" % cursor_name)
            found_any = True
        
        select_content = find_select(sentence)
        if select_content:
            print(select_content)
            found_any = True

        if found_any:
            print()
