#!/bin/bash
CMD_NAME=$(basename $0)

if [ $# -lt 1 ]
then
    echo "${CMD_NAME} [what] (extension) (where)"
    exit
fi

WHAT=$1
if [ $# -lt 2 ]
then
    EXT=
else
    EXT=$2
fi
if [ $# -lt 3 ]
then
    WHERE=.
else
    WHERE=$3
fi

if [ -z ${EXT} ]
then
    find ${WHERE} -type f \( -iname "*.h" -or -iname "*.hpp" -or -iname "*.c" -or -iname "*.cpp" -or -iname "*.cc" -or -iname "*.java" -or -iname "*.py" -or -iname "*.sh" -or -iname "*.sql" -or -iname "*.spc" -or -iname "*.bdy" -or -iname "*.prc" -or -iname "*.fnc" -or -iname "*.xml" -or -iname "*.ini" \) -exec egrep -Hnai "\<${WHAT}\>" {} \;
else
    find ${WHERE} -type f -iname "*.${EXT}" -exec egrep -Hnai "\<${WHAT}\>" {} \;
fi
