#!/bin/sh

source ./Config.sh

autoscan
mv configure.scan configure.in
sed -i "s/^AC_INIT.*$/AC_INIT([${PROG_NAME}], [${VERSION}])\nAM_INIT_AUTOMAKE([${PROG_NAME}], [${VERSION}])/" configure.in
sed -i "s/^AC_CONFIG_FILES.*$//" configure.in
sed -i "s/^AC_OUTPUT$/AC_CONFIG_FILES([Makefile])\nAC_OUTPUT/" configure.in

autoheader
aclocal
autoconf

SOURCES=`find . \( -name "*.h" -or -name "*.hpp" -or -name "*.c" -or -name "*.cpp" \) | xargs`
rm -f Makefile.am
echo "bin_PROGRAMS = ${PROG_NAME}" >> Makefile.am
echo "${PROG_NAME}_SOURCES = ${SOURCES}" >> Makefile.am
if [ -n "${DEFS}" ]
then
    echo "DEFS += ${DEFS}" >> Makefile.am
fi
if [ -n "${INCLUDES}" ]
then
    echo "INCLUDES = ${INCLUDES}" >> Makefile.am
fi
if [ -n "${LIBS}" ]
then
    echo "LIBS = ${LIBS}" >> Makefile.am
fi
touch NEWS README AUTHORS ChangeLog
automake --add-missing
