#!/bin/sh

if [ ! -f ./Config.sh ]
then
    echo "LIB_NAME=\"\"" >> ./Config.sh
    echo "VERSION=\"\"" >> ./Config.sh
    echo "DEFS=\"\"" >> ./Config.sh
    echo "INCLUDES=\"\"" >> ./Config.sh
    echo "LIBS=\"\"" >> ./Config.sh

    echo "Can't find \"Config.sh\", copied default."
    exit
fi

source ./Config.sh

autoscan
mv configure.scan configure.in
sed -i "s/^AC_INIT.*$/AC_INIT([${LIB_NAME}], [${VERSION}])\nAM_INIT_AUTOMAKE([${LIB_NAME}], [${VERSION}])\nAC_PROG_LIBTOOL\nAC_PROG_RANLIB/" configure.in
sed -i "s/^AC_CONFIG_FILES.*$//" configure.in
sed -i "s/^AC_OUTPUT$/AC_CONFIG_FILES([Makefile])\nAC_OUTPUT/" configure.in

autoheader
aclocal
autoconf

SOURCES=`find . \( -name "*.h" -or -name "*.hpp" -or -name "*.c" -or -name "*.cpp" \) | xargs`
rm -f Makefile.am
echo "lib_LTLIBRARIES = ${LIB_NAME}.la" >> Makefile.am
echo "${LIB_NAME}_la_SOURCES = ${SOURCES}" >> Makefile.am
if [ -n "${DEFS}" ]
then
    echo "DEFS += ${DEFS}" >> Makefile.am
fi
if [ -n "${INCLUDES}" ]
then
    echo "INCLUDES = ${INCLUDES}" >> Makefile.am
fi
if [ -n "${LIBS}" ]
then
    echo "LIBS = ${LIBS}" >> Makefile.am
fi
touch NEWS README AUTHORS ChangeLog
libtoolize
automake --add-missing
