#!/bin/sh

echo
echo "CpMf        -- Copy makefile"
echo "FindFr      -- Find from"
echo "Iconv       -- iconv"
echo "Man2Pdf     -- man to pdf"
echo "MergeLn     -- Merge lines"
echo "Modify      -- Modify"
echo "OpenPort    -- Open TCP/UDP port"
echo "Rename      -- Rename"
echo "RmLn        -- Remove lines"
echo "Valgrind    -- valgrind"
echo
