#!/bin/sh

echo
echo "CpMf        -- Copy makefile"
echo "FindFr      -- Find from"
echo "Iconv       -- iconv"
echo "Man2Pdf     -- man to pdf"
echo "MergeLn     -- Merge lines"
echo "Modify      -- Modify"
echo "OpenPort    -- Open TCP/UDP port"
echo "Pdb         -- Python debug"
echo "Rename      -- Rename"
echo "RmLn        -- Remove lines"
echo "Stp         -- Stap"
echo "Stpl        -- Stap list"
echo "Valgrind    -- valgrind"
echo "WatchStack  -- Watch program stacks"
echo
