#!/bin/sh
CMD_NAME=$(basename $0)

if [ $# -lt 2 ]
then
    echo "${CMD_NAME} [from charset] [to charset] [files]"
    exit
fi

FCHARSET=$1
shift
TCHARSET=$1
shift

for FILE in $@
do
    echo "Converting ${FILE}..."
    iconv -f ${FCHARSET} -t ${TCHARSET} ${FILE} > /tmp/iconv.tmp
    if [ $? -eq 0 ]
    then
        mv /tmp/iconv.tmp ${FILE}
    fi
done

