#!/bin/sh
CMD_NAME=$(basename $0)

if [ $# -lt 1 ]
then
    echo "${CMD_NAME} <section> [name]"
    exit
fi

if [ $# -ge 2 ]
then
    NAME=$2
    SECTION=$1
else
    NAME=$1
    SECTION=
fi

man -t ${SECTION} ${NAME} | ps2pdf - > ${NAME}.pdf

