#!/bin/sh
CMD_NAME=$(basename $0)

if [ $# -lt 1 ]
then
    echo "${CMD_NAME} [port] <protocol>"
    echo "protocol: \"tcp\" or \"udp\", default is \"tcp\""
    exit
fi

PROTOCOL=tcp
if [ $# -ge 2 ]
then
    PROTOCOL=$2
fi

sudo iptables -I INPUT -p ${PROTOCOL} --dport $1 -j ACCEPT
