#!/bin/sh
CMD_NAME=$(basename $0)

if [ $# -lt 2 ]
then
    echo "${CMD_NAME} [old_pattern] [new_pattern]"
    exit
fi

for oldname in *
do
    newname=${oldname//$1/$2}
    if [ "${newname}" != "${oldname}" ]
    then
        mv ${oldname} ${newname}
    fi
done
