#!/bin/sh
CMD_NAME=$(basename $0)

if [ $# -lt 1 ]
then
    echo "${CMD_NAME} [number]"
    exit
fi

FILENAME="rfc$1.txt"
if [ ! -r ${FILENAME} ]
then
    wget "http://www.ietf.org/rfc/rfc$1.txt"
fi

if [ -r ${FILENAME} ]
then
    vim ${FILENAME}
fi
