#!/bin/sh
CMD_NAME=$(basename $0)

if [ $# -lt 1 ]
then
    echo "${CMD_NAME} [interface] [expression]"
    exit
fi

INTERFACE=$1
shift
EXPRESSION=$*

sudo tcpdump -i ${INTERFACE} -X -n -nn ${EXPRESSION}
