#!/bin/sh

if [ $# -lt 1 ]
then
    FILES=*
else
    FILES=$*
fi

for FILE in ${FILES}
do
    if [ -f ${FILE} -a -r ${FILE} ]
    then
        echo "========================================"
        echo "* ${FILE}:"
        echo
        cat ${FILE}
        echo
    fi
done
